OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = populate.ml
INCDIRS = ../../lib
LIBDIRS = ../../lib
LIBS    = bigarray postgresql
OCAMLFLAGS = -w Aer -strict-sequence
RESULT  = populate

-include $(OCAMLMAKEFILE)
