OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = prompt.ml
INCDIRS = ../../lib
LIBDIRS = ../../lib
LIBS    = bigarray postgresql
OCAMLFLAGS = -w Aer -strict-sequence
THREADS = yes
RESULT  = prompt

-include $(OCAMLMAKEFILE)
