OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = cursor.ml
INCDIRS = ../../lib
LIBDIRS = ../../lib
LIBS    = bigarray postgresql
OCAMLFLAGS = -w Aer -strict-sequence
RESULT  = cursor

-include $(OCAMLMAKEFILE)
