OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = prompt_gtk.ml
INCDIRS = ../../lib
LIBDIRS = ../../lib
LIBS    = postgresql
OCAMLFLAGS = -w Aer -strict-sequence
PACKS   = lablgtk2
RESULT  = prompt_gtk

-include $(OCAMLMAKEFILE)
