OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = test_lo.ml
INCDIRS = ../../lib
LIBDIRS = ../../lib
LIBS    = bigarray postgresql
OCAMLFLAGS = -w Aer -strict-sequence
RESULT  = test_lo

-include $(OCAMLMAKEFILE)
