OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES = dump.ml
INCDIRS = ../../lib
LIBDIRS = ../../lib
LIBS    = bigarray postgresql
OCAMLFLAGS = -w Aer -strict-sequence
RESULT  = dump

-include $(OCAMLMAKEFILE)
